name: jmp-ui

replicas: 2

# custom branding for UI
brand:
  name: JMP
  msg: ""
  noun: Jump
  key: jmp

images:
  repository: harbor.v2.dcas.dev/dcas.dev/jmp-ui
  tag: master
  pullPolicy: Always
  imagePullSecrets:
    - name: v2-dcas.dev

ingress:
  enabled: true
  host: jmp.castive.dev
  # enforce HTTPS using HSTS (recommended)
  hsts: false

# network policy
netsec:
  enabled: false
  # label to allow traffic from
  source:
    app: traefik
  namespace:
    dev.dcas.netsec/name: default

nodeSelector: {}

tolerations: []

affinity: {}