kind: pipeline
name: default
type: kubernetes

steps:
  - name: audit
    image: harbor.v2.dcas.dev/library/drone-npm-audit
    pull: always
    settings:
      fix: true
  # BUILD OCI IMAGE
  - name: publish
    image: harbor.v2.dcas.dev/library/drone-kaniko
    pull: always
    settings:
      registry: harbor.v2.dcas.dev
      repo: dcas.dev/jmp-ui
      cache: true
      tags:
        - latest
        - ${DRONE_BRANCH/\//-}
        - ${DRONE_COMMIT_SHA}
      authjson_docker:
        from_secret: DOCKER_AUTH
trigger:
  when:
    event:
      - push