kind: pipeline
name: default
type: kubernetes

steps:
  # BUILD OCI IMAGE
  - name: publish
    image: harbor.v2.dcas.dev/infra/drone-kaniko:dcas-dev
    pull: always
    settings:
      registry: harbor.v2.dcas.dev
      repo: dcas.dev/jmp-ui
      cache: true
      tags:
        - latest
        - ${DRONE_BRANCH/\//-}
        - ${DRONE_COMMIT_SHA}
trigger:
  when:
    event:
      - push
