kind: pipeline
name: frontend

steps:
  # BUILD OCI IMAGE
  - name: publish
    image: harbor.v2.dcas.dev/library/drone-kaniko
    pull: always
    settings:
      registry: index.docker.io/djcass44
      repo: jmp-ui
      cache: true
      cache_repo: harbor.v2.dcas.dev/dcas.dev
      tags:
        - ${DRONE_BRANCH/\//-}
      authjson_docker:
        from_secret: DOCKER_AUTH
trigger:
  when:
    event:
      - push