kind: pipeline
name: frontend

steps:
  - name: build
    image: plugins/docker
    settings:
      repo: djcass44/jmp-ui
      tags:
        - ${DRONE_BRANCH}
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
trigger:
  when:
    event:
      - push