variables:
  TEST_DISABLED: 'true'
  POSTGRES_ENABLED: 'false'
  KANIKO_BUILD_ARGS: "NPM_REGISTRY=prism.dcas.dev/npm"
  STAGING_ENABLED: 'true'
  A11Y_ENABLED: 'true'
  CODE_QUALITY_NARK: 'true'
  NARK_URL: 'production-38-auto-deploy.go-nark-38-production.svc.cluster.local:8080'

include:
  - remote: 'https://gitlab.dcas.dev/open-source/gitlab-ci-templates/-/raw/master/auto/Auto-UI.gitlab-ci.yml'
