variables:
  CODE_QUALITY_DISABLED: 'true'
  TEST_DISABLED: 'true'
  POSTGRES_ENABLED: 'false'
  KANIKO_BUILD_ARGS: "NPM_REGISTRY=prism.dcas.dev/npm"
  STAGING_ENABLED: 'true'

include:
  - remote: 'https://gitlab.dcas.dev/open-source/gitlab-ci-templates/-/raw/master/auto/Auto-UI.gitlab-ci.yml'
