variables:
  TEST_DISABLED: 'true'
  STAGING_ENABLED: 'true'
  A11Y_ENABLED: 'true'
  AUTO_RELEASE_DISABLED: 'false'

mirror-master:
  extends: .mirror-image
  variables:
    MIRROR_SOURCE_IMAGE: "jmp/jmp-react:master"
    MIRROR_TARGET_IMAGE: "dcas.dev/jmp-ui:master"
    MIRROR_SOURCE_REGISTRY: "registry.dcas.dev"
    MIRROR_TARGET_REGISTRY: "harbor.v2.dcas.dev"

include:
  - remote: 'https://gitlab.com/av1o/gitlab-ci-templates/-/raw/master/auto/Auto-UI.gitlab-ci.yml'
  - remote: "https://gitlab.com/av1o/gitlab-ci-templates/-/raw/master/misc/OCI-Mirror.gitlab-ci.yml"
