apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: ui
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      automountServiceAccountToken: false
      {{- with .Values.images.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        fsGroup: 100
        runAsUser: 101
        runAsGroup: 101
      volumes:
        - name: tmp
          emptyDir: {}
      containers:
        - image: "{{ .Values.images.repository }}:{{ .Values.images.tag }}"
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          name: {{ .Values.name }}
          env:
            - name: JMP_API_URL
              value: {{ index .Values.ingress.host }}
            - name: JMP_API_SECURE
              value: "true"
            {{- with .Values.brand }}
            - name: JMP_BRAND_NAME
              value: {{ .name }}
            - name: JMP_BRAND_MSG
              value: {{ .msg }}
            - name: JMP_BRAND_NOUN
              value: {{ .noun }}
            - name: JMP_BRAND_KEY
              value: {{ .key }}
          {{- end }}
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: tmp
              mountPath: /var/tmp/nginx
          resources:
            requests:
              memory: 8Mi
              cpu: 10m
            limits:
              memory: 16Mi
              cpu: 50m
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          securityContext:
            runAsNonRoot: true
            privileged: false
            allowPrivilegeEscalation: false
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always